global_config:
  cmake_envs:
    CMAKE_CXX_COMPILER: "g++-7"
    MMDEPLOY_BUILD_SDK: "ON"
    MMDEPLOY_BUILD_SDK_PYTHON_API: "ON"
    MMDEPLOY_TARGET_DEVICES: '"cpu;cuda"'
    MMDEPLOY_TARGET_BACKENDS: "trt"
    CUDNN_DIR: "${CUDNN_DIR}"
    pplcv_DIR: ${pplcv_DIR}/cuda-build/install/lib/cmake/ppl

local_configs:
  - BUILD_NAME: "mmdeploy-many-linux-x86_64-cuda113-tensorrt8230"
    cmake_envs:
      TENSORRT_DIR: "${TENSORRT_DIR}"
      CUDA_TOOLKIT_ROOT_DIR: "/usr/local/cuda-11.3"
