global_config:
  cmake_envs:
    CMAKE_CXX_COMPILER: "g++-7"
    MMDEPLOY_BUILD_SDK: "ON"
    MMDEPLOY_BUILD_SDK_PYTHON_API: "ON"

local_configs:
  - BUILD_NAME: "mmdeploy-many-linux-x86_64-onnxruntime"
    cmake_envs:
      MMDEPLOY_TARGET_DEVICES: '"cpu"'
      MMDEPLOY_TARGET_BACKENDS: "ort"
      ONNXRUNTIME_DIR: "${ONNXRUNTIME_DIR}"
  - BUILD_NAME: "mmdeploy-many-linux-x86_64-cuda113-tensorrt8230"
    cmake_envs:
      MMDEPLOY_TARGET_DEVICES: '"cuda"'
      MMDEPLOY_TARGET_BACKENDS: "trt"
      TENSORRT_DIR: "${TENSORRT_DIR}"
      CUDA_TOOLKIT_ROOT_DIR: "/usr/local/cuda-11.3"
      CUDNN_DIR: "${CUDNN_DIR}"
      pplcv_DIR: ${pplcv_DIR}/cuda-build/install/lib/cmake/ppl
