global_config:
  cmake_flags: ['-G "Visual Studio 17 2022" -A x64 -T v143']
  cmake_envs:
    MMDEPLOY_BUILD_SDK: "ON"
    MMDEPLOY_BUILD_SDK_PYTHON_API: "ON"
    MMDEPLOY_TARGET_DEVICES: '"cpu"'
    MMDEPLOY_TARGET_BACKENDS: "ort"
    MMDEPLOY_CODEBASES: "all"

local_configs:
  - BUILD_NAME: "windows-cpu-ort8230"
    cmake_envs:
      ONNXRUNTIME_DIR: "%ONNXRUNTIME_DIR%"
